/*GET_USER_INFO: "GET_USER_INFO",
END_LOADING: "END_LOADING",
START_LOADING: "START_LOADING",
CHANGE_OFFSET: "CHANGE_OFFSET",
UPLOAD_AVATAR: "UPLOAD_AVATAR";*/
export const LOADING_MORE_FAILED='LOADING_MORE_FAILED';
export const CANCEL_INITLOADING='CANCEL_INITLOADING';
export const LOAD_MORE_USERS='LOAD_MORE_USERS';
export const GET_USERS= "GET_USERS";
export const CANCEL_LOADING= "CANCEL_LOADING";
export const LOAD_MORE= "LOAD_MORE";
export const DELETE_USER= "DELETE_USER";
export const BAN_USER= "BAN_USER";
export const UNBAN_USER= "UNBAN_USER";
export const ADD_ADMIN='ADD_ADMIN';
export const REMOVE_ADMIN='REMOVE_ADMIN';